### PR TITLE
modify makefile to add necessary libraries, remove some warnings

### PR DESCRIPTION
**Pull request by wlike**

### CODE REVIEW

**Comment by XingxingZhang** [comment]
Hi @wlike 

Thanks for the cleanup and I really appreciate that. 

But could you merge it to the "dev-cleanup" branch? There are more things need to be cleaned up. For example, most code in "rnnpg" overlaps with the code in "rnnpg-decoder" and "rnnpg-generator". There are also overlaps between "rnnpg-decoder" and "rnnpg-generator".

I plan to clean up these parts as well in the near future.

Cheers,

**Comment by wlike** [comment]
There are many redundant codes. Maybe the structure needs to be rearranged.

**Comment by wlike** [comment]
I've changed from master to dev-cleanup branch in the pull request.

2016-10-12 17:52 GMT+08:00 XingxingZhang notifications@github.com:

**Comment by wlike** [comment]
Thanks!

2016-11-14 3:30 GMT+08:00 XingxingZhang notifications@github.com:

**Pull request merged**
